name: Python Checks

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: uv sync
        
    - name: Lint with ruff
      run: uv run ruff check .
      
    - name: Run tests
      run: uv run pytest tests/
