name: Publish library

on:
  push:

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  publish:
    needs: checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: uv sync

    - name: Publish to pypi
      run: uv build
