name: Publish library

on:
  push:
    tags:
      - 'v*'  # This will match tags that start with 'v' (e.g., v1.0.0)
    branches:
      - main  # Only run on the main branch

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  publish:
    needs: checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: uv sync

    - name: Publish to pypi
      run: uv build

    - name: Publish to pypi
      run: uv publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
